include_keywords:
  - "Claude"
  - "ChatGPT"
  - "GPT"
  - "Gemini"
  - "AI"
  - "人工知能"
  - "機械学習"
  - "深層学習"
  - "ディープラーニング"
  - "AIエージェント"
  - "LLM"
  - "AIワークフロー"
  - "vibecoding"
  - "OpenAI"
  - "Anthropic"
  - "Google AI"

exclude_keywords:
  - "求人"
  - "採用"
  - "転職"
  - "募集"
  - "バイト"
  - "アルバイト"